# ============================================================
# Podfile for Yodo1 MAS ANE iOS Build
# ============================================================
# This Podfile pulls in the Yodo1MasFull pod (v4.17.1) which
# includes all ad network mediation adapters.
#
# The resulting frameworks are used to build the static library
# that gets packaged into the ANE.
#
# Usage:
#   cd native_src/ios
#   pod install --repo-update
#   Then build via build_ios.sh
# ============================================================

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Yodo1Games/MAS-Spec.git'

platform :ios, '13.0'

target 'Yodo1MasANE' do
  use_frameworks! :linkage => :static

  pod 'Yodo1MasFull', '4.17.1'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
